# Stage: Development Environment
FROM golang:1.23-alpine

# Install dependencies
RUN apk update && apk add --no-cache git build-base

# Install Air for hot reload
RUN go install github.com/air-verse/air@latest

# Set working directory
WORKDIR /app
COPY . .
RUN go mod download

# Expose application port
EXPOSE 8080

# Start the Go app with Air for hot reload
CMD ["air"]